server:
  #port: ${port:10086}
  port: 10086
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka  #eureka 服务地址
      #defaultZone: ${defaultZon:http://127.0.0.1:10086/eureka}
    fetch-registry: false        #不拉取服务
    register-with-eureka: false  #不注册自己